### PR TITLE
PullREQ_demo

### PR DESCRIPTION
**Pull request by costiborghi**
How could I create a pull request? @GiovanniIacopetti

### CODE REVIEW

**Comment by GiovanniIacopetti** [comment]
Like this, but now you made a branch (_forked_) of your "Ragainst" repository, if you _fork_ the whole CorsoStatisticaR repository, you can change those files and send the pull request to me (you are the owner of this repo, you have to accept your own pull request

**Comment by GiovanniIacopetti** [comment]
schermata 2018-03-23 alle 11 23 15

This is what I see from here :) it tells me that I don't have the permission to merge your pull request, because you're the owner

**Comment by costiborghi** [comment]
What about now?

**Comment by GiovanniIacopetti** [comment]
Adesso dovresti fare lo stesso con la pagina del sito,
modificando la pagina delle FAQ (il file .Rmd e aggiungendo una nuova domanda),
poi fare la pull request (che a quel punto devo accettare io)

**Pull request merged**
